#!/usr/bin/env python3
"""Generate docs/config.example.yaml from ServerConfig Pydantic schema defaults.

Run from repo root: uv run python scripts/generate_config_example.py
Or: make config-example
"""

from pathlib import Path

import yaml


def main() -> None:
    from mcp_server_tree_sitter.config_schema import ServerConfig

    config = ServerConfig()
    data = config.model_dump()

    # Optional: omit None values for cleaner YAML (allowed_extensions omitted when unset)
    def drop_none(d: dict) -> dict:
        return {k: drop_none(v) if isinstance(v, dict) else v for k, v in d.items() if v is not None}

    data = drop_none(data)

    out_path = Path(__file__).resolve().parent.parent / "docs" / "config.example.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        "# MCP Tree-sitter Server — example configuration\n"
        "# All keys and values are the schema defaults (ServerConfig).\n"
        "# Optional: security.allowed_extensions (list of extensions; omit for all).\n"
        "# Copy to ~/.config/tree-sitter/config.yaml or pass via --config.\n"
        "# Generated by scripts/generate_config_example.py — do not edit by hand.\n"
        "\n"
    )

    yaml_content = yaml.dump(
        data,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )

    out_path.write_text(header + yaml_content, encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
